"use client";

import { useEffect, useState } from "react";
import { formatDistanceToNow } from "date-fns";
import { getComments, submitComment } from "@/lib/api";

interface Comment { id: number; author_name: string; content: string; created_at: string; replies?: Comment[]; }
interface CommentApiResponse { data?: Comment[]; }
export function CommentSection({ modelType, modelId }: { modelType: string; modelId: string | number }) {
  const [comments, setComments] = useState<Comment[]>([]); const [loading, setLoading] = useState(true); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [content, setContent] = useState(""); const [sending, setSending] = useState(false); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); try { const result = await getComments(modelType, modelId) as CommentApiResponse | Comment[]; setComments(Array.isArray(result) ? result : result.data || []); } finally { setLoading(false); } }
  useEffect(() => { let cancelled = false; getComments(modelType, modelId).then((result) => { if (!cancelled) { const response = result as CommentApiResponse | Comment[]; setComments(Array.isArray(response) ? response : response.data || []); } }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [modelId, modelType]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSending(true); setNotice(""); try { await submitComment(modelType, modelId, { name, email, content }); setNotice("Your comment has been submitted and is pending approval."); setContent(""); await load(); } catch { setNotice("We could not submit your comment. Please try again."); } finally { setSending(false); } }
  const field = "w-full border border-slate-300 bg-white px-3 py-3 text-sm text-[var(--ink)] outline-none focus:border-[var(--blue)]";
  return <section className="mt-14 border-t border-slate-200 pt-10"><h2 className="text-2xl font-extrabold tracking-[-.04em] text-[var(--ink)]">Comments ({comments.length})</h2><form onSubmit={submit} className="mt-6 border border-slate-200 bg-[var(--mist)] p-5"><div className="grid gap-3 sm:grid-cols-2"><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Your name" className={field} /><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Your email" className={field} /></div><textarea required rows={4} value={content} onChange={(event) => setContent(event.target.value)} placeholder="Share your thoughts…" className={`${field} mt-3`} /><button disabled={sending} className="button-primary mt-3 disabled:opacity-60">{sending ? "Submitting…" : "Post comment"} →</button>{notice && <p className="mt-3 text-sm text-[var(--muted)]">{notice}</p>}</form><div className="mt-7 space-y-4">{loading ? <p className="text-sm text-[var(--muted)]">Loading comments…</p> : comments.length ? comments.map((comment) => <CommentItem key={comment.id} comment={comment} />) : <p className="text-sm text-[var(--muted)]">No comments yet. Be the first to share your thoughts.</p>}</div></section>;
}
function CommentItem({ comment, reply = false }: { comment: Comment; reply?: boolean }) { return <article className={`${reply ? "ml-6 border-l border-slate-200 pl-5" : ""} border-b border-slate-100 pb-4`}><div className="flex justify-between gap-4"><h3 className="text-sm font-extrabold text-[var(--ink)]">{comment.author_name}</h3><time className="shrink-0 text-xs text-[var(--muted)]">{formatDistanceToNow(new Date(comment.created_at), { addSuffix: true })}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[var(--ink-soft)]">{comment.content}</p>{comment.replies?.map((item) => <div key={item.id} className="mt-4"><CommentItem comment={item} reply /></div>)}</article>; }
