services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: nova-app
        container_name: nova-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: nova_m
            DB_USERNAME: sail
            DB_PASSWORD: password
        networks:
            - nova-network
        depends_on:
            - db


    web:
        image: nginx:alpine
        container_name: nova-web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - nova-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: nova-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: nova_m
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: sail
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - nova-network

    # Optional: Adminer to manage DB
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        networks:
            - nova-network

    npm:
        image: node:20
        container_name: nova-npm
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: sh -c "npm install && npm run dev -- --host"
        ports:
            - "5173:5173"
        networks:
            - nova-network

networks:
    nova-network:
        driver: bridge

volumes:
    db-data:
