import type { Metadata } from "next";
import { getContactInfo } from "@/lib/api";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { ContactForm } from "@/components/contact/ContactForm";
import { TcRequestForm } from "@/components/contact/TcRequestForm";

export async function generateMetadata(): Promise<Metadata> { const data = await getContactInfo(); return { title: data.page.meta_title || "Contact us", description: data.page.meta_description || "Get in touch with our team" }; }
export default async function ContactPage() { const { page, services } = await getContactInfo(); return <><Breadcrumb title={page.breadcrumb_title || page.title} image={page.image} items={[{ label: "Contact" }]} /><section className="page-section page-section--mist"><div className="site-container"><div className="mb-12 max-w-2xl"><span className="eyebrow">Start a conversation</span><h2 className="display-title text-[clamp(2.2rem,4vw,4.2rem)]">{page.contact_title || "Let’s build what’s next."}</h2>{page.contact_description && <p className="section-copy mt-5">{page.contact_description}</p>}</div><div className="mb-12 grid gap-4 md:grid-cols-3">{page.contact_address && <ContactCard icon="⌖" title="Visit" value={page.contact_address} />}{page.contact_email && <ContactCard icon="✉" title="Email" value={page.contact_email} href={`mailto:${page.contact_email}`} />}{page.contact_phone && <ContactCard icon="◔" title="Call" value={page.contact_phone} href={`tel:${page.contact_phone}`} />}</div><div className="grid items-start gap-8 lg:grid-cols-2"><div><span className="eyebrow">General enquiry</span><h3 className="mb-5 text-2xl font-extrabold tracking-[-.04em] text-[var(--ink)]">Tell us about your goals.</h3><ContactForm /></div><div><span className="eyebrow">Project enquiry</span><h3 className="mb-5 text-2xl font-extrabold tracking-[-.04em] text-[var(--ink)]">Request a consultation.</h3><TcRequestForm services={services} /></div></div></div></section></>; }
function ContactCard({ icon, title, value, href }: { icon: string; title: string; value: string; href?: string }) { const content = <><span className="text-xl text-[var(--blue)]">{icon}</span><div><h3 className="text-xs font-extrabold uppercase tracking-[.14em] text-[var(--ink)]">{title}</h3><p className="mt-1 text-sm leading-5 text-[var(--muted)]">{value}</p></div></>; return href ? <a href={href} className="content-card flex gap-4 p-6 transition hover:border-[#9ab8e9]">{content}</a> : <div className="content-card flex gap-4 p-6">{content}</div>; }
