import Link from "next/link";
import { ContentImage } from "@/components/ui/ContentImage";
import { resolveProjectPresentationImage } from "@/lib/demoMedia";
import type { Project } from "@/lib/types";

export function ProjectsShowcase({ projects, title, subtitle, eyebrow, buttonText, buttonUrl, viewAllText }: { projects: Project[]; title: string | null; subtitle: string | null; eyebrow?: string | null; buttonText?: string | null; buttonUrl?: string | null; viewAllText?: string }) {
  if (!projects.length) return null;
  return <section className="page-section project-showcase"><div className="site-container"><div className="mb-9 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="eyebrow">{eyebrow || "Projects"}</span><h2 className="display-title text-[clamp(2.2rem,3.8vw,3.9rem)]">{title || "Selected work"}</h2>{subtitle && <p className="section-copy mt-3">{subtitle}</p>}</div><Link href={buttonUrl || "/projects"} className="arrow-link shrink-0">{buttonText || viewAllText || "View all projects"}</Link></div><div className="grid gap-6 md:grid-cols-2">{projects.slice(0, 2).map((project, index) => <Link key={project.id} href={`/projects/${project.slug}`} className="group"><article><div className="relative aspect-[1.52] overflow-hidden bg-slate-200"><ContentImage src={resolveProjectPresentationImage(project.image, index)} alt={project.title} sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition duration-500 group-hover:scale-105" fallbackClassName="project-image-placeholder" /></div><div className="flex gap-5 pt-4"><div className="min-w-0 flex-1">{project.category && <p className="text-[.62rem] font-extrabold uppercase tracking-[.14em] text-[var(--blue)]">{project.category}</p>}<h3 className="mt-1 text-xl font-extrabold tracking-[-.035em] text-[var(--ink)]">{project.title}</h3>{project.description && <p className="mt-2 line-clamp-2 text-sm leading-5 text-[var(--muted)]">{project.description}</p>}{project.client && <p className="mt-3 text-xs font-semibold text-[var(--muted)]">{project.client}</p>}</div><span className="mt-4 flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-[#9ab8e9] text-lg text-[var(--blue)] transition group-hover:bg-[var(--blue)] group-hover:text-white">→</span></div></article></Link>)}</div></div></section>;
}
