import Image from "next/image";
import Link from "next/link";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { shouldRenderServiceImage } from "@/lib/demoMedia";
import type { Service } from "@/lib/types";

export function ServicesGrid({ services, title, subtitle, eyebrow, buttonText, buttonUrl }: { services: Service[]; title: string | null; subtitle: string | null; eyebrow?: string | null; buttonText?: string | null; buttonUrl?: string | null }) {
  if (!services.length) return null;
  return <section className="page-section bg-white"><div className="site-container grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:gap-16"><div><span className="eyebrow">{eyebrow || "Our expertise"}</span><h2 className="display-title text-[clamp(2.15rem,3.7vw,3.8rem)]">{title || "The right expertise. Connected."}</h2>{subtitle && <p className="section-copy mt-6">{subtitle}</p>}<Link href={buttonUrl || "/services"} className="arrow-link mt-8">{buttonText || "Explore all services"}</Link></div><div className="grid gap-3 sm:grid-cols-2">{services.slice(0, 4).map((service, index) => <Link key={service.id} href={`/services/${service.slug}`} className="content-card group min-h-[190px] p-6 transition hover:-translate-y-1 hover:border-[#a9c4ff] hover:shadow-lg"><span className="text-xs font-extrabold text-[var(--muted)]">{String(index + 1).padStart(2, "0")}</span><div className="mt-5 flex items-start justify-between gap-3"><div className="text-[var(--blue)]">{shouldRenderServiceImage(service.image) ? <Image src={service.image!} alt="" width={30} height={30} className="h-7 w-7 object-contain" /> : <ServiceIcon icon={service.icon} className="h-7 w-7" />}</div><span className="text-xl text-[var(--blue)] transition-transform group-hover:translate-x-1">→</span></div><h3 className="mt-4 text-base font-extrabold text-[var(--ink)]">{service.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-5 text-[var(--muted)]">{service.subtitle || service.description || ""}</p></Link>)}</div></div></section>;
}
