"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { submitTcRequest } from "@/lib/api";
import type { Service } from "@/lib/types";
import { getDictionary } from "@/lib/dictionary";

const schema = z.object({ email: z.string().email("Please enter a valid email."), service_id: z.string().optional(), budget_range: z.string().optional(), timeline: z.string().optional(), description: z.string().min(10, "Please add a little more detail."), website_url: z.string().optional() });
type Values = z.infer<typeof schema>;
export function TcRequestForm({ services, locale = "en" }: { services: Service[]; locale?: string }) {
  const t = getDictionary(locale).contact.consultation; const [file, setFile] = useState<File | null>(null); const [fileKey, setFileKey] = useState(0); const [status, setStatus] = useState<"idle" | "loading" | "success" | "error">("idle"); const [notice, setNotice] = useState("");
  const { register, handleSubmit, reset, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { budget_range: "5000", timeline: "Flexible" } });
  async function onSubmit(values: Values) { setStatus("loading"); const data = new FormData(); Object.entries(values).forEach(([key, value]) => data.set(key, value || "")); if (file) data.set("attached_file", file); try { const response = await submitTcRequest(data); setStatus("success"); setNotice(response.message); reset(); setFile(null); setFileKey((value) => value + 1); } catch { setStatus("error"); setNotice(getDictionary(locale).contact.error); } }
  const input = "mt-1.5 w-full border border-slate-300 bg-white px-3 py-3 text-sm text-[var(--ink)] outline-none transition focus:border-[var(--blue)]";
  return <form onSubmit={handleSubmit(onSubmit)} className="content-card p-6 sm:p-8"><input type="text" className="hidden" tabIndex={-1} autoComplete="off" {...register("website_url")} /><Label label={t.email} error={errors.email?.message}><input type="email" className={input} {...register("email")} /></Label><Label label={t.selectService}><select className={input} {...register("service_id")}><option value="">Select a service</option>{services.map((service) => <option key={service.id} value={service.id}>{service.title}</option>)}</select></Label><div className="grid gap-4 sm:grid-cols-2"><Label label={t.budget || "Budget range"}><select className={input} {...register("budget_range")}><option value="1000">Up to $1,000</option><option value="5000">$1,000–$5,000</option><option value="10000">$5,000–$10,000</option><option value="50000">$10,000+</option></select></Label><Label label={t.timeline || "Timeline"}><select className={input} {...register("timeline")}><option value="ASAP">ASAP</option><option value="1-3 months">1–3 months</option><option value="3-6 months">3–6 months</option><option value="Flexible">Flexible</option></select></Label></div><Label label={t.details} error={errors.description?.message}><textarea rows={4} className={input} placeholder={t.detailsPlaceholder} {...register("description")} /></Label><label className="mt-4 block text-sm font-bold text-[var(--ink)]">{t.attach || "Attachment"}<span className="ml-1 font-normal text-[var(--muted)]">(optional)</span><input key={fileKey} type="file" className="mt-1.5 block w-full border border-dashed border-slate-300 bg-white p-3 text-sm text-[var(--muted)] file:mr-3 file:border-0 file:bg-[var(--blue-pale)] file:px-3 file:py-1.5 file:text-xs file:font-bold file:text-[var(--blue)]" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>{file && <p className="mt-2 text-xs text-[var(--muted)]">Attached: {file.name}</p>}<button disabled={status === "loading"} className="button-primary mt-5 w-full disabled:opacity-60">{status === "loading" ? "Sending…" : "Send project request"} →</button>{status !== "idle" && <p aria-live="polite" className={`mt-4 text-sm ${status === "success" ? "text-emerald-700" : "text-red-600"}`}>{notice}</p>}</form>;
}
function Label({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="mt-4 block text-sm font-bold text-[var(--ink)]">{label}{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>; }
