"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import type { Project } from "@/lib/types";
import { ContentImage } from "@/components/ui/ContentImage";
import { resolveProjectPresentationImage } from "@/lib/demoMedia";

export function ProjectsGrid({ projects, categories, activeCategory }: { projects: Project[]; categories: string[]; activeCategory?: string }) {
  const router = useRouter();
  return <section className="page-section page-section--mist"><div className="site-container">{categories.length > 0 && <div className="mb-10 flex flex-wrap gap-2"><button onClick={() => router.push("/projects")} className={`rounded border px-4 py-2 text-xs font-extrabold ${!activeCategory ? "border-[var(--blue)] bg-[var(--blue)] text-white" : "border-slate-300 text-[var(--ink)] hover:border-[var(--blue)]"}`}>All</button>{categories.map((category) => <button key={category} onClick={() => router.push(`/projects?category=${encodeURIComponent(category)}`)} className={`rounded border px-4 py-2 text-xs font-extrabold ${activeCategory === category ? "border-[var(--blue)] bg-[var(--blue)] text-white" : "border-slate-300 text-[var(--ink)] hover:border-[var(--blue)]"}`}>{category}</button>)}</div>}<div className="grid gap-7 md:grid-cols-2">{projects.map((project, index) => <Link key={project.id} href={`/projects/${project.slug}`} className="group"><article><div className="relative aspect-[1.5] overflow-hidden bg-slate-200"><ContentImage src={resolveProjectPresentationImage(project.image, index)} alt={project.title} sizes="(max-width: 768px) 100vw, 50vw" className="object-cover transition duration-500 group-hover:scale-105" fallbackClassName="project-image-placeholder" /></div><div className="flex gap-4 pt-4"><div className="min-w-0 flex-1">{project.category && <p className="text-[.62rem] font-extrabold uppercase tracking-[.15em] text-[var(--blue)]">{project.category}</p>}<h2 className="mt-1 text-2xl font-extrabold tracking-[-.04em] text-[var(--ink)]">{project.title}</h2>{project.description && <p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{project.description}</p>}</div><span className="mt-3 flex h-9 w-9 shrink-0 items-center justify-center rounded-full border border-[#9ab8e9] text-lg text-[var(--blue)] group-hover:bg-[var(--blue)] group-hover:text-white">→</span></div></article></Link>)}</div>{!projects.length && <p className="py-16 text-center text-[var(--muted)]">No projects found.</p>}</div></section>;
}
