import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import DOMPurify from "isomorphic-dompurify";
import { getBlog } from "@/lib/api";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { CommentSection } from "@/components/blog/CommentSection";

interface Props { params: Promise<{ slug: string }> }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const { blog } = await getBlog(slug); return { title: blog.meta_title || blog.title, description: blog.meta_description || blog.excerpt || "", openGraph: blog.og_image ? { images: [{ url: blog.og_image }] } : undefined }; }
export default async function BlogDetailPage({ params }: Props) { const { slug } = await params; const { blog, recent_blogs: recent } = await getBlog(slug); return <><Breadcrumb title={blog.title} items={[{ label: "Insights", href: "/blog" }, { label: blog.title }]} /><section className="page-section bg-white"><div className="site-container grid gap-12 lg:grid-cols-[1fr_300px]"><article>{blog.image && <div className="relative mb-8 aspect-[1.8] overflow-hidden bg-slate-200"><Image src={blog.image} alt={blog.title} fill sizes="(max-width:1024px) 100vw, 70vw" className="object-cover" unoptimized={blog.image.includes("localhost") || blog.image.includes("127.0.0.1")} /></div>}<div className="mb-8 flex flex-wrap items-center gap-3 text-xs text-[var(--muted)]">{blog.category && <span className="font-extrabold uppercase tracking-[.14em] text-[var(--blue)]">{blog.category}</span>}{blog.published_at && <span>{new Date(blog.published_at).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</span>}{blog.author && <span>By {blog.author.name}</span>}</div><div className="rich-content text-[1.05rem]" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(blog.content || blog.excerpt || "") }} /><CommentSection modelType="blog" modelId={blog.slug} /></article><aside><div className="sticky top-24 border-t-2 border-[var(--blue)] bg-[var(--mist)] p-6"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-[var(--blue)]">Keep reading</p><h2 className="mt-2 text-xl font-extrabold text-[var(--ink)]">Recent insights</h2><div className="mt-5 space-y-5">{recent.map((item) => <Link key={item.id} href={`/blog/${item.slug}`} className="group block"><p className="text-xs font-extrabold uppercase tracking-[.13em] text-[var(--blue)]">{item.category || "Insight"}</p><h3 className="mt-1 text-sm font-bold leading-5 text-[var(--ink)] group-hover:text-[var(--blue)]">{item.title}</h3></Link>)}</div></div></aside></div></section></>; }
