import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import DOMPurify from "isomorphic-dompurify";
import { getService } from "@/lib/api";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { shouldRenderServiceImage } from "@/lib/demoMedia";

interface Props { params: Promise<{ slug: string }> }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const { service } = await getService(slug); return { title: service.meta_title || service.title, description: service.meta_description || service.subtitle || "", openGraph: service.og_image ? { images: [{ url: service.og_image }] } : undefined }; }
export default async function ServiceDetailPage({ params }: Props) { const { slug } = await params; const { service, all_services } = await getService(slug); return <><Breadcrumb title={service.title} items={[{ label: "Services", href: "/services" }, { label: service.title }]} /><section className="page-section bg-white"><div className="site-container grid gap-12 lg:grid-cols-[1fr_300px]"><article>{shouldRenderServiceImage(service.image) ? <div className="relative mb-9 aspect-[1.8] overflow-hidden bg-slate-200"><Image src={service.image!} alt={service.title} fill sizes="(max-width: 1024px) 100vw, 70vw" className="object-cover" unoptimized={service.image!.includes("localhost") || service.image!.includes("127.0.0.1")} /></div> : <div className="mb-9 flex aspect-[1.8] items-center justify-center bg-[var(--blue-pale)] text-[var(--blue)]"><ServiceIcon icon={service.icon} className="h-20 w-20" /></div>}<div className="rich-content text-[1.05rem]" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(service.description || service.subtitle || "") }} /></article><aside><div className="sticky top-24 border-t-2 border-[var(--blue)] bg-[var(--mist)] p-6"><p className="text-xs font-extrabold uppercase tracking-[.15em] text-[var(--blue)]">Explore</p><h2 className="mt-2 text-xl font-extrabold text-[var(--ink)]">All services</h2><nav className="mt-5 space-y-1">{all_services.map((item) => <Link key={item.id} href={`/services/${item.slug}`} className={`block border-b py-3 text-sm font-bold ${item.slug === slug ? "border-[var(--blue)] text-[var(--blue)]" : "border-slate-200 text-[var(--ink-soft)] hover:text-[var(--blue)]"}`}>{item.title}</Link>)}</nav><Link href="/contact" className="button-primary mt-6 w-full">Start a project →</Link></div></aside></div></section></>; }
