import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { getServices } from "@/lib/api";
import { Breadcrumb } from "@/components/ui/Breadcrumb";
import { ServiceIcon } from "@/components/ui/ServiceIcon";
import { shouldRenderServiceImage } from "@/lib/demoMedia";

export async function generateMetadata(): Promise<Metadata> { const data = await getServices(); return { title: data.page.meta_title || "Our Services", description: data.page.meta_description || "Professional IT services and technology solutions" }; }
export default async function ServicesPage() { const data = await getServices(); return <><Breadcrumb title={data.page.title} image={data.page.image} items={[{ label: "Services" }]} /><section className="page-section page-section--mist"><div className="site-container"><div className="mb-10 max-w-2xl"><span className="eyebrow">Our expertise</span><h2 className="display-title text-[clamp(2.2rem,4vw,4.2rem)]">Built for the way your business works.</h2></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.services.map((service, index) => <Link key={service.id} href={`/services/${service.slug}`} className="content-card group min-h-[260px] p-7 transition hover:-translate-y-1 hover:border-[#9abbf5] hover:shadow-xl"><p className="text-xs font-extrabold text-[var(--muted)]">{String(index + 1).padStart(2, "0")}</p><div className="mt-7 flex items-start justify-between"><div className="text-[var(--blue)]">{shouldRenderServiceImage(service.image) ? <Image src={service.image!} alt="" width={34} height={34} className="h-8 w-8 object-contain" /> : <ServiceIcon icon={service.icon} className="h-8 w-8" />}</div><span className="text-xl text-[var(--blue)] transition group-hover:translate-x-1">→</span></div><h3 className="mt-7 text-xl font-extrabold tracking-[-.04em] text-[var(--ink)]">{service.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-[var(--muted)]">{service.subtitle || service.description || ""}</p></Link>)}</div></div></section></>; }
